daysUntilStale: 60
daysUntilClose: 30
exemptLabels:
  - "notice"
  - "keep active"
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. This means this issue is resolved or nobody else has had 
  this issue or feature request. It will be closed if no further activity occurs 
  within 30 days, so if this is still relevant, please let us know!
closeComment: >
  Closing this issue after 90 days of no activity. You may reopen this issue if
  it's still a think to be looked at!
